# Base docker build
FROM lom-slave-bullseye:1234

# Copy the cache data to host
From scratch as output
COPY --from=lom-slave-bullseye:1234 /cache.tgz cache.tgz

# Clean up the cache data
FROM lom-slave-bullseye:1234 as final
RUN rm /cache.tgz

