# Base docker build
FROM sonic-slave-bullseye:c0cd3b2fb18

# Copy the cache data to host
From scratch as output
COPY --from=sonic-slave-bullseye:c0cd3b2fb18 /cache.tgz cache.tgz

# Clean up the cache data
FROM sonic-slave-bullseye:c0cd3b2fb18 as final
RUN rm /cache.tgz

