#! /bin/bash

echo ""
echo "==========================="
echo "Self-extracting LoM archive"
echo "==========================="

export TMPDIR=`mktemp -d /tmp/selfextract.XXXXXX`

ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`

tail -n+$ARCHIVE $0 | tar xzv -C $TMPDIR

CDIR=`pwd`
cd $TMPDIR
./install/LoM-install.sh

cd $CDIR
#rm -rf $TMPDIR
echo "TMPDIR is $TMPDIR"

exit 0

__ARCHIVE_BELOW__
